//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealTimeUnit.ServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.IRtuDriver")]
    public interface IRtuDriver {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRtuDriver/InitRtuDriver", ReplyAction="http://tempuri.org/IRtuDriver/InitRtuDriverResponse")]
        void InitRtuDriver(string publicKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRtuDriver/InitRtuDriver", ReplyAction="http://tempuri.org/IRtuDriver/InitRtuDriverResponse")]
        System.Threading.Tasks.Task InitRtuDriverAsync(string publicKey);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IRtuDriver/UpdateValue")]
        void UpdateValue(int address, double value, byte[] signature);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IRtuDriver/UpdateValue")]
        System.Threading.Tasks.Task UpdateValueAsync(int address, double value, byte[] signature);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRtuDriverChannel : RealTimeUnit.ServiceReference.IRtuDriver, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RtuDriverClient : System.ServiceModel.ClientBase<RealTimeUnit.ServiceReference.IRtuDriver>, RealTimeUnit.ServiceReference.IRtuDriver {
        
        public RtuDriverClient() {
        }
        
        public RtuDriverClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RtuDriverClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RtuDriverClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RtuDriverClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void InitRtuDriver(string publicKey) {
            base.Channel.InitRtuDriver(publicKey);
        }
        
        public System.Threading.Tasks.Task InitRtuDriverAsync(string publicKey) {
            return base.Channel.InitRtuDriverAsync(publicKey);
        }
        
        public void UpdateValue(int address, double value, byte[] signature) {
            base.Channel.UpdateValue(address, value, signature);
        }
        
        public System.Threading.Tasks.Task UpdateValueAsync(int address, double value, byte[] signature) {
            return base.Channel.UpdateValueAsync(address, value, signature);
        }
    }
}
